from __future__ import annotations

from typing import Dict, List, Tuple

import yaml
from jinja2 import Environment

DAG_TEMPLATE = '''"""{{ description }} — generated by airflow-dag-gen, do not edit by hand."""
from datetime import datetime, timedelta

from airflow import DAG
{% if has_bash %}from airflow.operators.bash import BashOperator
{% endif %}{% if has_python %}from airflow.operators.python import PythonOperator
{% endif %}{% if has_sql %}from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
{% endif %}
default_args = {
    "owner": "{{ owner }}",
    "retries": {{ retries }},
    "retry_delay": timedelta(minutes={{ retry_delay_minutes }}),
}

with DAG(
    dag_id="{{ dag_id }}",
    description="{{ description }}",
    schedule="{{ schedule }}",
    start_date=datetime({{ start_date.year }}, {{ start_date.month }}, {{ start_date.day }}),
    catchup={{ catchup }},
    default_args=default_args,
    tags={{ tags }},
) as dag:
{% for task in tasks %}
{% if task.type == "bash" %}    {{ task.id }} = BashOperator(
        task_id="{{ task.id }}",
        bash_command="{{ task.command }}",
    )
{% elif task.type == "python" %}    {{ task.id }} = PythonOperator(
        task_id="{{ task.id }}",
        python_callable={{ task.callable }},
    )
{% elif task.type == "sql" %}    {{ task.id }} = SQLExecuteQueryOperator(
        task_id="{{ task.id }}",
        conn_id="{{ task.conn_id }}",
        sql="""{{ task.sql }}""",
    )
{% endif %}{% endfor %}
{% for edge in edges %}    {{ edge[0] }} >> {{ edge[1] }}
{% endfor %}'''


def validate_config(cfg: Dict) -> List[str]:
    """CI-style validation: structural errors before any code is generated."""
    errors: List[str] = []
    for key in ("dag_id", "schedule", "tasks"):
        if key not in cfg:
            errors.append(f"missing required key: {key}")
    tasks = cfg.get("tasks", [])
    ids = [t.get("id") for t in tasks]
    if len(ids) != len(set(ids)):
        errors.append("duplicate task ids")
    known = set(ids)
    for t in tasks:
        if not t.get("id", "").isidentifier():
            errors.append(f"task id '{t.get('id')}' is not a valid Python identifier")
        ttype = t.get("type")
        if ttype not in ("bash", "python", "sql"):
            errors.append(f"task '{t.get('id')}': unknown type '{ttype}' (bash|python|sql)")
        required = {"bash": "command", "python": "callable", "sql": "sql"}.get(ttype or "", None)
        if required and required not in t:
            errors.append(f"task '{t.get('id')}': type '{ttype}' requires '{required}'")
        for dep in t.get("depends_on", []):
            if dep not in known:
                errors.append(f"task '{t.get('id')}': unknown dependency '{dep}'")
    cycle = _find_cycle(tasks)
    if cycle:
        errors.append(f"dependency cycle: {' -> '.join(cycle)}")
    return errors


def _find_cycle(tasks: List[Dict]) -> List[str]:
    deps = {t["id"]: list(t.get("depends_on", [])) for t in tasks if "id" in t}
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {k: WHITE for k in deps}
    path: List[str] = []

    def visit(node: str) -> List[str]:
        color[node] = GRAY
        path.append(node)
        for dep in deps.get(node, []):
            if color.get(dep) == GRAY:
                return path[path.index(dep):] + [dep]
            if color.get(dep) == WHITE:
                found = visit(dep)
                if found:
                    return found
        color[node] = BLACK
        path.pop()
        return []

    for node in deps:
        if color[node] == WHITE:
            found = visit(node)
            if found:
                return found
    return []


def topo_levels(tasks: List[Dict]) -> Dict[str, int]:
    """Task -> depth level for drawing the DAG left-to-right."""
    deps = {t["id"]: list(t.get("depends_on", [])) for t in tasks}
    levels: Dict[str, int] = {}

    def level(node: str) -> int:
        if node not in levels:
            levels[node] = 1 + max((level(d) for d in deps.get(node, [])), default=-1)
        return levels[node]

    for t in deps:
        level(t)
    return levels


def generate_dag(cfg: Dict) -> Tuple[str, List[str]]:
    """YAML config dict -> (DAG source code, validation errors). Code is '' when errors exist."""
    errors = validate_config(cfg)
    if errors:
        return "", errors
    tasks = cfg["tasks"]
    edges = [(dep, t["id"]) for t in tasks for dep in t.get("depends_on", [])]
    types = {t["type"] for t in tasks}
    start = cfg.get("start_date", "2026-01-01")
    y, m, d = (int(x) for x in str(start).split("-"))

    class _D:
        year, month, day = y, m, d

    code = Environment().from_string(DAG_TEMPLATE).render(
        dag_id=cfg["dag_id"],
        description=cfg.get("description", cfg["dag_id"]),
        schedule=cfg["schedule"],
        owner=cfg.get("owner", "data-eng"),
        retries=cfg.get("retries", 2),
        retry_delay_minutes=cfg.get("retry_delay_minutes", 5),
        catchup=cfg.get("catchup", False),
        tags=cfg.get("tags", ["generated"]),
        start_date=_D,
        tasks=tasks,
        edges=edges,
        has_bash="bash" in types,
        has_python="python" in types,
        has_sql="sql" in types,
    )
    return code, []


def load_yaml(text: str) -> Dict:
    return yaml.safe_load(text)
