name: CI

on:
  push:
    paths:
      - "data-infra-toolkit/schema-diff/**"
  pull_request:
    paths:
      - "data-infra-toolkit/schema-diff/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-infra-toolkit/schema-diff
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install ruff
      - run: ruff check .
      - run: ruff format --check .
